gdrive files upload checkpoints/seed0_CD/ --recursive
gdrive files upload checkpoints/seed1_CD/ --recursive
gdrive files upload checkpoints/seed2_CD/ --recursive
gdrive files upload checkpoints/seed3_CD/ --recursive
gdrive files upload checkpoints/seed4_CD/ --recursive
gdrive files upload checkpoints/seedF_-4_3_m_CD/ --recursive
gdrive files upload checkpoints/seedF_m_-3_m_CD/ --recursive
gdrive files upload checkpoints/seedI_-4_3_d_CD/ --recursive
gdrive files upload checkpoints/seedI_-4_3_m_CD/ --recursive
gdrive files upload checkpoints/seedP_-3_3_n_CD/ --recursive
